name: PlayerMotinor-Ultra
version: '0.1.1'
main: net.Mirik9724.playermonitor_ultra.PlayerMonitorUltra
api-version: '1.18'
commands:
  playermonitor-ultra:
    aliases: pmu
    description: Search data by nickname, IP or UUID
    usage: /pmu <subcommand> <nick or uuid or ip>
    permission: pmu.admin